In [5]:
import pandas as pd
from pathlib import Path
#
folder = Path(".")  # <-- ganti dengan folder CSV Anda


kolom_str = ["assignment_id", "level_2_code", "kategori", "kode_kbli", "nama_usaha"]

kolom_int = [
    "metrik_tenaga_kerja",
    "metrik_upah_gaji",
    "metrik_biaya_produksi",
    "metrik_biaya_pembelian",
    "metrik_biaya_operasional",
    "metrik_biaya_non_operasional",
    "metrik_total_pengeluaran",
    "metrik_pendapatan_barang_jasa",
    "metrik_pendapatan_lainnya",
    "metrik_nilai_tambah",
    "metrik_total_aset",
    "metrik_output",
]

kolom_real = [
    "rasio_biaya_pembelian_barang_terhadap_omzet",
    "rasio_ntb",
    "produktivitas",
]

# Tidak disebut: kategori/flag, diperlakukan string
kolom_lain_str = [
    "reklasifikasi_skala_usaha",
    "flag_rasio_1_output_aset",
    "flag_rasio_2_upah_ntb",
    "flag_rasio_3_ntb_output",
    "flag_kategori_P_dan_U",
]

In [6]:
# Baca semua sebagai string dulu, konversi sesudahnya (aman dari error tipe saat ada nilai kosong/aneh)
dtype_baca = {c: str for c in kolom_str + kolom_int + kolom_real + kolom_lain_str}

frames = []
for f in sorted(folder.glob("*.csv")):
    d = pd.read_csv(f, dtype=dtype_baca, encoding="utf-8-sig", low_memory=False)
    d.columns = d.columns.astype(str).str.strip()
    d["sumber_file"] = f.name
    frames.append(d)
    print(f"{f.name}: {d.shape}")

df = pd.concat(frames, ignore_index=True)

# Buang baris header yang ikut terbaca sebagai data
df = df[df["assignment_id"] != "assignment_id"]

# String: strip, nilai kosong jadi None
for c in kolom_str + kolom_lain_str:
    df[c] = (
        df[c]
        .astype("string")
        .str.strip()
        .replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})
    )

# Integer: pakai Int64 (nullable) supaya NaN tidak memaksa jadi float
for c in kolom_int:
    df[c] = pd.to_numeric(df[c], errors="coerce").round().astype("Int64")

# Real: float64
for c in kolom_real:
    df[c] = pd.to_numeric(df[c], errors="coerce").astype("float64")

df = df.drop_duplicates().reset_index(drop=True)

print(df.shape)
print(df.dtypes)
df.head()

Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluaran Pendapatan Nilai Tambah per usaha - SPLIT 1.csv: (216846, 26)
Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluaran Pendapatan Nilai Tambah per usaha - SPLIT 2.csv: (214268, 26)
Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluaran Pendapatan Nilai Tambah per usaha - SPLIT 3.csv: (216396, 26)
Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluaran Pendapatan Nilai Tambah per usaha - SPLIT 4.csv: (214589, 26)
Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluaran Pendapatan Nilai Tambah per usaha - SPLIT 5.csv: (214608, 26)
Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluaran Pendapatan Nilai Tambah per usaha - SPLIT 6.csv: (211964, 26)
Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluaran Pendapatan Nilai Tambah per usaha - SPLIT 7.csv: (215429, 26)
Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluaran Pendapatan Nilai Tambah per usaha - SPLIT 8.csv: (216950, 26)
Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluaran Pendapatan Nilai Tambah per usaha - SPLIT 9.csv: (130047, 26)
(1850931, 26)
assignment_id                                  string[python]
level_2_code                                   string[python]
kategori                                       string[python]
kode_kbli                                      string[python]
nama_usaha                                     string[python]
metrik_tenaga_kerja                                     Int64
metrik_upah_gaji                                        Int64
metrik_biaya_produksi                                   Int64
metrik_biaya_pembelian                                  Int64
metrik_biaya_operasional                                Int64
metrik_biaya_non_operasional                            Int64
metrik_total_pengeluaran                                Int64
metrik_pendapatan_barang_jasa                           Int64
metrik_pendapatan_lainnya                               Int64
metrik_nilai_tambah                                     Int64
metrik_total_aset                                       Int64
metrik_output                                           Int64
rasio_biaya_pembelian_barang_terhadap_omzet           float64
reklasifikasi_skala_usaha                      string[python]
rasio_ntb                                             float64
produktivitas                                         float64
flag_rasio_1_output_aset                       string[python]
flag_rasio_2_upah_ntb                          string[python]
flag_rasio_3_ntb_output                        string[python]
flag_kategori_P_dan_U                          string[python]
sumber_file                                            object
dtype: object

,assignment_id,level_2_code,kategori,kode_kbli,nama_usaha,metrik_tenaga_kerja,metrik_upah_gaji,metrik_biaya_produksi,metrik_biaya_pembelian,metrik_biaya_operasional,...,metrik_output,rasio_biaya_pembelian_barang_terhadap_omzet,reklasifikasi_skala_usaha,rasio_ntb,produktivitas,flag_rasio_1_output_aset,flag_rasio_2_upah_ntb,flag_rasio_3_ntb_output,flag_kategori_P_dan_U,sumber_file
0,0067eab8-97e4-4169-940c-6b7d124b102f,1601,A,01111,PERKEBUNAN JAGUNG MARDANI,1,0,35000000,0,8000000,...,86000000,0.0,Mikro,0.500000,8.600000e+07,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...
1,00754e8b-9421-4536-ac01-778f0ee3b0c4,1601,A,01111,UTP TANAMAN PANGAN (ISMANTO),2,0,14880000,0,8160000,...,0,NaN,Mikro,NaN,0.000000e+00,<NA>,1,<NA>,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...
2,008baf68-cf1b-44a5-9015-3ef04664306e,1601,A,01111,UTP TANAMAN PANGAN JAGUNG (MARKUS WARJU),7,5000000,7080000,0,1500000,...,59000000,0.0,Mikro,0.854576,8.428571e+06,1,1,0,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...
3,00a48eda-54fa-427f-8fcb-a1ebf42440bf,1601,A,01111,PERKEBUNAN JAGUNG (ASMARA),1,0,4000000,0,3000000,...,12100000,0.0,Mikro,0.421488,1.210000e+07,<NA>,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...
4,00e1b203-ea5a-4c97-832c-221264a478a2,1601,A,01111,PERKEBUNAN JAGUNG,2,0,24000000,0,6000000,...,45000000,0.0,Mikro,0.333333,2.250000e+07,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...

In [10]:
BASE_URL = (
    "https://fasih-sm.bps.go.id/app/assignment/fd68e454-ba45-4b85-8205-f3bf777ded24/"
)

# 1. Kolom link, ditaruh paling kiri
df.insert(0, "link", BASE_URL + df["assignment_id"].astype("string"))

# 2. Dua kolom di ujung kanan
df["status_penyelesaian"] = False  # nanti jadi checkbox di Excel
df["keterangan"] = ""  # kosong

# 3. Pastikan dua kolom baru benar-benar paling ujung (sumber_file digeser sebelum keduanya)
akhir = ["status_penyelesaian", "keterangan"]
df = df[[c for c in df.columns if c not in akhir] + akhir]

df.head()

,link,assignment_id,level_2_code,kategori,kode_kbli,nama_usaha,metrik_tenaga_kerja,metrik_upah_gaji,metrik_biaya_produksi,metrik_biaya_pembelian,...,reklasifikasi_skala_usaha,rasio_ntb,produktivitas,flag_rasio_1_output_aset,flag_rasio_2_upah_ntb,flag_rasio_3_ntb_output,flag_kategori_P_dan_U,sumber_file,status_penyelesaian,keterangan
0,https://fasih-sm.bps.go.id/app/assignment/fd68...,0067eab8-97e4-4169-940c-6b7d124b102f,1601,A,01111,PERKEBUNAN JAGUNG MARDANI,1,0,35000000,0,...,Mikro,0.500000,8.600000e+07,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1,https://fasih-sm.bps.go.id/app/assignment/fd68...,00754e8b-9421-4536-ac01-778f0ee3b0c4,1601,A,01111,UTP TANAMAN PANGAN (ISMANTO),2,0,14880000,0,...,Mikro,NaN,0.000000e+00,<NA>,1,<NA>,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
2,https://fasih-sm.bps.go.id/app/assignment/fd68...,008baf68-cf1b-44a5-9015-3ef04664306e,1601,A,01111,UTP TANAMAN PANGAN JAGUNG (MARKUS WARJU),7,5000000,7080000,0,...,Mikro,0.854576,8.428571e+06,1,1,0,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
3,https://fasih-sm.bps.go.id/app/assignment/fd68...,00a48eda-54fa-427f-8fcb-a1ebf42440bf,1601,A,01111,PERKEBUNAN JAGUNG (ASMARA),1,0,4000000,0,...,Mikro,0.421488,1.210000e+07,<NA>,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
4,https://fasih-sm.bps.go.id/app/assignment/fd68...,00e1b203-ea5a-4c97-832c-221264a478a2,1601,A,01111,PERKEBUNAN JAGUNG,2,0,24000000,0,...,Mikro,0.333333,2.250000e+07,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,

In [11]:
# SPLIT Data
import re
from pathlib import Path
import pandas as pd

out_dir = Path("output_excel")
out_dir.mkdir(exist_ok=True)


def nama_aman(teks, maks=31):
    t = re.sub(r"[\[\]:*?/\\]", "_", str(teks)).strip()
    return (t or "KOSONG")[:maks]


kolom_export = [c for c in df.columns if c != "sumber_file"]
kolom_teks = {"link", "assignment_id", "level_2_code", "kode_kbli"}
idx_status = kolom_export.index("status_penyelesaian")

for lv2, df_lv2 in df.groupby("level_2_code", dropna=False):
    path = out_dir / f"{nama_aman(lv2, 100)}.xlsx"
    sheet_terpakai = set()

    # strings_to_urls=False: link ditulis sebagai teks biasa (Excel membatasi 65.530 hyperlink per sheet)
    with pd.ExcelWriter(
        path, engine="xlsxwriter", engine_kwargs={"options": {"strings_to_urls": False}}
    ) as writer:
        wb = writer.book
        fmt_header = wb.add_format({"bold": True, "bg_color": "#D9E1F2", "border": 1})
        fmt_teks = wb.add_format({"num_format": "@"})

        for kat, d in df_lv2.groupby("kategori", dropna=False):
            nama = nama_aman(kat)
            asli, n = nama, 1
            while nama.lower() in sheet_terpakai:
                n += 1
                nama = f"{asli[:28]}_{n}"
            sheet_terpakai.add(nama.lower())

            d = d[kolom_export].reset_index(drop=True)
            d.to_excel(writer, sheet_name=nama, index=False)
            ws = writer.sheets[nama]

            for j, col in enumerate(d.columns):
                ws.write(0, j, col, fmt_header)
            ws.freeze_panes(1, 0)
            ws.autofilter(0, 0, len(d), len(d.columns) - 1)

            # Checkbox pada kolom status_penyelesaian (default FALSE / tidak dicentang)
            for i in range(len(d)):
                ws.insert_checkbox(
                    i + 1, idx_status, bool(d.at[i, "status_penyelesaian"])
                )

            for j, col in enumerate(d.columns):
                lebar = max(
                    len(str(col)), d[col].head(1000).astype(str).str.len().max()
                )
                ws.set_column(
                    j, j, min(lebar + 2, 40), fmt_teks if col in kolom_teks else None
                )

    print(
        f'{path.name}: {df_lv2["kategori"].nunique(dropna=False)} sheet, {len(df_lv2)} baris'
    )

1601.xlsx: 20 sheet, 82965 baris
1602.xlsx: 19 sheet, 198726 baris
1603.xlsx: 19 sheet, 147663 baris
1604.xlsx: 19 sheet, 120462 baris
1605.xlsx: 19 sheet, 101185 baris
1606.xlsx: 19 sheet, 140359 baris
1607.xlsx: 21 sheet, 181378 baris
1608.xlsx: 19 sheet, 115653 baris
1609.xlsx: 20 sheet, 232730 baris
1610.xlsx: 19 sheet, 87563 baris
1611.xlsx: 20 sheet, 71486 baris
1612.xlsx: 19 sheet, 40088 baris
1613.xlsx: 19 sheet, 44860 baris
1671.xlsx: 21 sheet, 174596 baris
1672.xlsx: 20 sheet, 33334 baris
1673.xlsx: 19 sheet, 41607 baris
1674.xlsx: 19 sheet, 36276 baris

In [44]:
df2 = df[(df["metrik_nilai_tambah"] <= -5000000) & (df["flag_rasio_3_ntb_output"] == "1")]

In [45]:
df2

,link,assignment_id,level_2_code,kategori,kode_kbli,nama_usaha,metrik_tenaga_kerja,metrik_upah_gaji,metrik_biaya_produksi,metrik_biaya_pembelian,...,reklasifikasi_skala_usaha,rasio_ntb,produktivitas,flag_rasio_1_output_aset,flag_rasio_2_upah_ntb,flag_rasio_3_ntb_output,flag_kategori_P_dan_U,sumber_file,status_penyelesaian,keterangan
20,https://fasih-sm.bps.go.id/app/assignment/fd68...,02b22ead-5084-4021-b00a-48ca676a2b89,1601,A,01111,MENANAM JAGUNG HIBRIDA,2,0,5000000,0,...,Mikro,-17.000000,250000.0,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
252,https://fasih-sm.bps.go.id/app/assignment/fd68...,21c7adfd-2fb0-4db7-8c6e-eab507ce6ae8,1601,A,01111,KEBUN JAGUNG HIBRIDA,1,0,50000000,0,...,Mikro,-29.000000,2000000.0,0,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
457,https://fasih-sm.bps.go.id/app/assignment/fd68...,3cf67f33-9ee7-41eb-b98e-1dc3ac52036e,1601,A,01111,UTP TANAMAN PANGAN,2,0,60000000,0,...,Mikro,-0.500000,24000000.0,<NA>,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
530,https://fasih-sm.bps.go.id/app/assignment/fd68...,47241035-8ee2-40a0-91f4-35ace0ec80e5,1601,A,01111,PERTANIAN JAGUNG,2,0,12000000,0,...,Mikro,-2.141104,2037500.0,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
593,https://fasih-sm.bps.go.id/app/assignment/fd68...,501c2d36-bd14-41c4-a365-73c70d26c773,1601,A,01111,PERTANIAN JAGUNG,2,0,26000000,0,...,Mikro,-0.375000,10000000.0,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1849934,https://fasih-sm.bps.go.id/app/assignment/fd68...,762f5d7e-de0c-4830-894c-ef857ea9d084,1674,T,95320,BENGKEL MOTOR (WINDRA),1,0,720000000,0,...,Mikro,-1.500000,300000000.0,<NA>,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1849943,https://fasih-sm.bps.go.id/app/assignment/fd68...,7c7ef73f-fa0f-4827-9299-420a80a0199d,1674,T,95320,BENGKEL MOTOR AL-HADI MOTOR,2,7200000,120000000,0,...,Mikro,-1.448555,25950000.0,<NA>,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1850174,https://fasih-sm.bps.go.id/app/assignment/fd68...,f06f8647-8b36-4744-afc8-7fbfd4912016,1674,T,95320,BENGKEL (ANDRE SAPUTRA),1,0,126000000,0,...,Mikro,-20.100000,6000000.0,<NA>,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1850372,https://fasih-sm.bps.go.id/app/assignment/fd68...,dd0a2f2a-2205-4a48-a758-9e2c8bb16bcf,1674,T,96100,LAUNDRY VILIHAN,2,4200000,156000000,0,...,Mikro,-25.406000,3000000.0,<NA>,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1850623,https://fasih-sm.bps.go.id/app/assignment/fd68...,f071fa0a-d7ec-431e-8b50-39108cd53a7e,1674,T,96210,BARBER SHOP BIAN,3,378000000,120000000,0,...,Mikro,-0.750000,24000000.0,<NA>,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,

In [17]:
df2.to_excel('usaha_nilai_tambah_minus_10jt.xlsx')

In [46]:
df3 = df[(df["metrik_output"] >= 1000000000) & (df["flag_rasio_3_ntb_output"] == "1")]

In [47]:
df3

,link,assignment_id,level_2_code,kategori,kode_kbli,nama_usaha,metrik_tenaga_kerja,metrik_upah_gaji,metrik_biaya_produksi,metrik_biaya_pembelian,...,reklasifikasi_skala_usaha,rasio_ntb,produktivitas,flag_rasio_1_output_aset,flag_rasio_2_upah_ntb,flag_rasio_3_ntb_output,flag_kategori_P_dan_U,sumber_file,status_penyelesaian,keterangan
121,https://fasih-sm.bps.go.id/app/assignment/fd68...,10a4e500-5390-478e-9d92-ddce7ec8963d,1601,A,01111,PETANI JAGUNG,2,0,500000,0,...,UMK,0.999500,6.000000e+09,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1027,https://fasih-sm.bps.go.id/app/assignment/fd68...,92192412-9166-4bb4-8c84-f8a2677874bc,1601,A,01111,PERKEBUNAN JAGUNG ( EVA LISDIANA),2,0,14000000,0,...,UMK,0.993824,1.700000e+09,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
4222,https://fasih-sm.bps.go.id/app/assignment/fd68...,a43d58e7-589d-477b-b51e-7c6c20b569e9,1601,A,01135,PERTANIAN KEBUN SINGKONG,6,50000000,30000000,0,...,UB,0.999600,2.083333e+10,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
6136,https://fasih-sm.bps.go.id/app/assignment/fd68...,0353d598-5041-4548-a33d-beca9c0f6d89,1601,A,01262,KEBUN SAWIT,15,564480000,660000000,0,...,Mikro,0.333715,1.164667e+08,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
6296,https://fasih-sm.bps.go.id/app/assignment/fd68...,1763575c-9a1b-4602-85a9-82aa36e98112,1601,A,01262,UTP PERKEBUNAN KELAPA SAWIT (JONI ARISANDI),5,54000000,0,0,...,Mikro,0.975490,2.448000e+08,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1850211,https://fasih-sm.bps.go.id/app/assignment/fd68...,2378c4e0-697f-4335-9598-dbbbb151c419,1674,T,95400,BENGKEL ADAM,9,421200000,0,0,...,Mikro,0.971800,1.333333e+08,0,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1850233,https://fasih-sm.bps.go.id/app/assignment/fd68...,e70d42e0-9b81-4030-9a31-2a057ebbc37c,1674,T,95400,BENGKEL JERRY PUTRAKA,1,0,0,0,...,UMK,0.999771,1.050000e+10,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1850656,https://fasih-sm.bps.go.id/app/assignment/fd68...,178e1580-bb0a-431a-95b5-ea42da5381e0,1674,T,96220,SKINFIDENCE,11,286000000,130000000,0,...,Mikro,0.858974,9.218182e+07,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1850776,https://fasih-sm.bps.go.id/app/assignment/fd68...,f0b2d5b4-7bf1-4361-b1fe-e2e5f7485939,1674,T,96220,KLINIK PRATAMA BENING'S (OKKY PRATAMA),23,820800000,0,0,...,UMK,0.906127,2.660870e+08,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1850784,https://fasih-sm.bps.go.id/app/assignment/fd68...,132884bb-087a-4b0e-86c9-481f3d41e463,1674,T,96230,CLEOPATRA SPA,17,300000000,100000000,0,...,Mikro,0.791667,7.058824e+07,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,

In [21]:
df3.to_excel('')

,link,assignment_id,level_2_code,kategori,kode_kbli,nama_usaha,metrik_tenaga_kerja,metrik_upah_gaji,metrik_biaya_produksi,metrik_biaya_pembelian,...,reklasifikasi_skala_usaha,rasio_ntb,produktivitas,flag_rasio_1_output_aset,flag_rasio_2_upah_ntb,flag_rasio_3_ntb_output,flag_kategori_P_dan_U,sumber_file,status_penyelesaian,keterangan
121,https://fasih-sm.bps.go.id/app/assignment/fd68...,10a4e500-5390-478e-9d92-ddce7ec8963d,1601,A,01111,PETANI JAGUNG,2,0,500000,0,...,UMK,0.999500,6.000000e+09,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1027,https://fasih-sm.bps.go.id/app/assignment/fd68...,92192412-9166-4bb4-8c84-f8a2677874bc,1601,A,01111,PERKEBUNAN JAGUNG ( EVA LISDIANA),2,0,14000000,0,...,UMK,0.993824,1.700000e+09,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1378,https://fasih-sm.bps.go.id/app/assignment/fd68...,c5932b87-e2c5-4292-aad3-42a49ba59dea,1601,A,01111,UTP TANAMAN PANGAN JAGUNG (FERLAN ADI SAPUTRA),26,360000000,144000000,0,...,Mikro,0.897368,7.015385e+07,<NA>,1,0,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
4222,https://fasih-sm.bps.go.id/app/assignment/fd68...,a43d58e7-589d-477b-b51e-7c6c20b569e9,1601,A,01135,PERTANIAN KEBUN SINGKONG,6,50000000,30000000,0,...,UB,0.999600,2.083333e+10,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
6117,https://fasih-sm.bps.go.id/app/assignment/fd68...,008cccb9-d618-4da4-a2c3-87e9a5472061,1601,A,01262,"SURYA BINTANG INDONESIA, PT",677,27954000000,3591476130,0,...,UM,0.868236,4.845180e+07,1,1,0,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1850656,https://fasih-sm.bps.go.id/app/assignment/fd68...,178e1580-bb0a-431a-95b5-ea42da5381e0,1674,T,96220,SKINFIDENCE,11,286000000,130000000,0,...,Mikro,0.858974,9.218182e+07,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1850702,https://fasih-sm.bps.go.id/app/assignment/fd68...,6b58e8d5-bc37-4386-a6b3-418c545b81d8,1674,T,96220,DERMAWISE SKIN CENTER,9,306000000,1440000000,0,...,UMK,0.682051,5.200000e+08,1,1,0,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1850776,https://fasih-sm.bps.go.id/app/assignment/fd68...,f0b2d5b4-7bf1-4361-b1fe-e2e5f7485939,1674,T,96220,KLINIK PRATAMA BENING'S (OKKY PRATAMA),23,820800000,0,0,...,UMK,0.906127,2.660870e+08,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1850784,https://fasih-sm.bps.go.id/app/assignment/fd68...,132884bb-087a-4b0e-86c9-481f3d41e463,1674,T,96230,CLEOPATRA SPA,17,300000000,100000000,0,...,Mikro,0.791667,7.058824e+07,1,1,1,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,
1850785,https://fasih-sm.bps.go.id/app/assignment/fd68...,426d7460-5ce0-46e3-8e23-c627a67ef802,1674,T,96230,PILATES & JAPANESE SPA (TUTI MAHARANI),10,540000000,1152000000,0,...,UMK,0.383721,2.064000e+08,<NA>,1,0,0,Tabel 3 (MIKRO). Usaha Tenaga Kerja Pengeluara...,False,

In [28]:
import sqlite3

DB_PATH = "usaha.db"

df_sql = df.copy()
df_sql["status_penyelesaian"] = df_sql["status_penyelesaian"].astype(
    int
)  # SQLite tidak punya boolean: 0/1

# Tipe kolom eksplisit di SQLite
dtype_sql = {}
for c in df_sql.columns:
    if c in kolom_int or c == "status_penyelesaian":
        dtype_sql[c] = "INTEGER"
    elif c in kolom_real:
        dtype_sql[c] = "REAL"
    else:
        dtype_sql[c] = "TEXT"

with sqlite3.connect(DB_PATH) as con:
    df_sql.to_sql(
        "usaha",
        con,
        if_exists="replace",
        index=False,
        dtype=dtype_sql,
        chunksize=50_000,
    )
    # Index agar filter cepat
    con.execute("CREATE INDEX IF NOT EXISTS idx_lv2 ON usaha(level_2_code)")
    con.execute("CREATE INDEX IF NOT EXISTS idx_kat ON usaha(kategori)")
    con.execute("CREATE INDEX IF NOT EXISTS idx_aid ON usaha(assignment_id)")
    con.commit()

    print(con.execute("SELECT COUNT(*) FROM usaha").fetchone())

(1850931,)

In [29]:
con.close()